---
downloads: ~/.ansible-downloads/

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
dockitems_persist: []

dotfiles_repo: git@github.com:asharman/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/code/github.com/asharman/dotfiles
dotfiles_files:
  - .gitconfig

homebrew_installed_packages:
  - mas

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alacritty
  - 1password

mas_installed_apps:
  - { id: 1569813296, name: "1Password Safari Extension"}
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
